/*
 * Chaos
 *
 * Management API (Central System)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchBuild {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "dockerfile")]
    pub dockerfile: String,
    #[serde(rename = "arch")]
    pub arch: Vec<serde_json::Value>,
}

impl BatchBuild {
    pub fn new(path: String, dockerfile: String, arch: Vec<serde_json::Value>) -> BatchBuild {
        BatchBuild {
            path,
            dockerfile,
            arch,
        }
    }
}


