/*
 * Chaos
 *
 * Management API (Central System)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BatchProject {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "domain")]
    pub domain: String,
}

impl BatchProject {
    pub fn new(name: String, domain: String) -> BatchProject {
        BatchProject {
            name,
            domain,
        }
    }
}


