/*
 * Chaos
 *
 * Management API (Central System)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ClustersLocation {
    #[serde(rename = "city")]
    pub city: String,
    #[serde(rename = "continent")]
    pub continent: String,
    #[serde(rename = "country")]
    pub country: String,
}

impl ClustersLocation {
    pub fn new(city: String, continent: String, country: String) -> ClustersLocation {
        ClustersLocation {
            city,
            continent,
            country,
        }
    }
}


