/*
 * Chaos
 *
 * Management API (Central System)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentsFunctions {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<crate::models::DeploymentsBuild>,
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "route", skip_serializing_if = "Option::is_none")]
    pub route: Option<crate::models::DeploymentsRoute>,
}

impl DeploymentsFunctions {
    pub fn new(name: String, description: String, image: String) -> DeploymentsFunctions {
        DeploymentsFunctions {
            name,
            description,
            build: None,
            image,
            route: None,
        }
    }
}


