/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// AuthTokenPatch : API auth token patch



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthTokenPatch {
    /// Name of token
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Token expiration duration in days. 0 - token will never expire
    #[serde(rename = "expiry_duration", skip_serializing_if = "Option::is_none")]
    pub expiry_duration: Option<i32>,
}

impl AuthTokenPatch {
    /// API auth token patch
    pub fn new() -> AuthTokenPatch {
        AuthTokenPatch {
            name: None,
            expiry_duration: None,
        }
    }
}


