/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// BadRequestResponse : Bad request



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BadRequestResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "fields")]
    pub fields: Box<models::BadRequestResponseFields>,
}

impl BadRequestResponse {
    /// Bad request
    pub fn new(message: String, fields: models::BadRequestResponseFields) -> BadRequestResponse {
        BadRequestResponse {
            message,
            fields: Box::new(fields),
        }
    }
}


