/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ConflictResponse : Conflict Response

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConflictResponse {
    #[serde(rename = "message")]
    pub message: String,
}

impl ConflictResponse {
    /// Conflict Response
    pub fn new(message: String) -> ConflictResponse {
        ConflictResponse {
            message,
        }
    }
}


