/*
 * Chaos
 *
 * Management API - Central user exposed system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateProjectFunctionsRequestBodySchema {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "build")]
    pub build: Box<crate::models::CreateProjectFunctionsRequestBodySchemaBuild>,
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "route")]
    pub route: Box<crate::models::CreateProjectFunctionsRequestBodySchemaRoute>,
    #[serde(rename = "location")]
    pub location: Box<crate::models::CreateProjectFunctionsRequestBodySchemaLocation>,
}

impl CreateProjectFunctionsRequestBodySchema {
    pub fn new(name: String, description: String, build: crate::models::CreateProjectFunctionsRequestBodySchemaBuild, image: String, route: crate::models::CreateProjectFunctionsRequestBodySchemaRoute, location: crate::models::CreateProjectFunctionsRequestBodySchemaLocation) -> CreateProjectFunctionsRequestBodySchema {
        CreateProjectFunctionsRequestBodySchema {
            name,
            description,
            build: Box::new(build),
            image,
            route: Box::new(route),
            location: Box::new(location),
        }
    }
}


