/*
 * Chaos
 *
 * Management API - Central user exposed system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateProjectFunctionsRequestBodySchemaBuild {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "dockerfile")]
    pub dockerfile: String,
    #[serde(rename = "arch")]
    pub arch: Vec<String>,
}

impl CreateProjectFunctionsRequestBodySchemaBuild {
    pub fn new(path: String, dockerfile: String, arch: Vec<String>) -> CreateProjectFunctionsRequestBodySchemaBuild {
        CreateProjectFunctionsRequestBodySchemaBuild {
            path,
            dockerfile,
            arch,
        }
    }
}


