/*
 * Chaos
 *
 * Management API - Central user exposed system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateProjectRequestBodySchema {
    #[serde(rename = "org")]
    pub org: f32,
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateProjectRequestBodySchema {
    pub fn new(org: f32, name: String) -> CreateProjectRequestBodySchema {
        CreateProjectRequestBodySchema {
            org,
            name,
        }
    }
}


