/*
 * Chaos
 *
 * Management API - Central user exposed system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateProjectFunctionsRequestBodySchemaLocation {
    #[serde(rename = "aws")]
    pub aws: Box<crate::models::CreateProjectFunctionsRequestBodySchemaLocationAws>,
}

impl CreateProjectFunctionsRequestBodySchemaLocation {
    pub fn new(aws: crate::models::CreateProjectFunctionsRequestBodySchemaLocationAws) -> CreateProjectFunctionsRequestBodySchemaLocation {
        CreateProjectFunctionsRequestBodySchemaLocation {
            aws: Box::new(aws),
        }
    }
}


