/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// Date : Object date information



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Date {
    /// UTC creation datetime (ISO 8601 date format)
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// UTC update datetime (ISO 8601 date format)
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Date {
    /// Object date information
    pub fn new(created_at: String, updated_at: String) -> Date {
        Date {
            created_at,
            updated_at,
        }
    }
}


