/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// FunctionEnv : Environment variable for function

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FunctionEnv {
    /// Key name
    #[serde(rename = "name")]
    pub name: String,
    /// Reference for the secret, it's split up into 4 main parts; - [1] \"projects:\" - This references which resource type the secret is within - [2] \"0a6b9ff3-6807-4820-b94b-5e1d7efcdd93\" - The project UUID the secret is within - [3] \"MY_SECRET\" - The name of the secret - [4] \"0\" - The revision of the secret to use 
    #[serde(rename = "reference")]
    pub reference: String,
}

impl FunctionEnv {
    /// Environment variable for function
    pub fn new(name: String, reference: String) -> FunctionEnv {
        FunctionEnv {
            name,
            reference,
        }
    }
}


