/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// FunctionCompliance : Tagged requirements for compliance; soc2 = SOC2 compliant data centers ipv6 = Function can work within an ipv6 *only* cluster 

#[allow(unused_imports)]
use crate::models;

/// Tagged requirements for compliance; soc2 = SOC2 compliant data centers ipv6 = Function can work within an ipv6 *only* cluster 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FunctionCompliance {
    #[serde(rename = "soc2")]
    Soc2,
    #[serde(rename = "ipv6")]
    Ipv6,

}

impl ToString for FunctionCompliance {
    fn to_string(&self) -> String {
        match self {
            Self::Soc2 => String::from("soc2"),
            Self::Ipv6 => String::from("ipv6"),
        }
    }
}

impl Default for FunctionCompliance {
    fn default() -> FunctionCompliance {
        Self::Soc2
    }
}




