/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// FunctionSize : Size of function, required CPU and Memory

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FunctionSize {
    /// CPU in 0.1 vCPU increments, for a whole vCPU specify 1024 Must be in multiples of 128, with the same multiplier as memory 
    #[serde(rename = "cpu")]
    pub cpu: i32,
    /// Memory in 128 MB increments, values are integer always in MB Must be in multiples of 128, with the same multiplier as CPU 
    #[serde(rename = "memory")]
    pub memory: i32,
}

impl FunctionSize {
    /// Size of function, required CPU and Memory
    pub fn new(cpu: i32, memory: i32) -> FunctionSize {
        FunctionSize {
            cpu,
            memory,
        }
    }
}


