/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FunctionRoute {
    /// Can be a regular expression
    #[serde(rename = "path")]
    pub path: String,
    /// HTTP Verb(s) for this function
    #[serde(rename = "methods")]
    pub methods: Vec<String>,
    /// The route weight for consideration
    #[serde(rename = "weight")]
    pub weight: i32,
}

impl FunctionRoute {
    pub fn new(path: String, methods: Vec<String>, weight: i32) -> FunctionRoute {
        FunctionRoute {
            path,
            methods,
            weight,
        }
    }
}


