/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FunctionDeploymentBody {
    #[serde(rename = "location")]
    pub location: Box<models::Location>,
    #[serde(rename = "replicas")]
    pub replicas: Box<models::FunctionReplicas>,
}

impl FunctionDeploymentBody {
    pub fn new(location: models::Location, replicas: models::FunctionReplicas) -> FunctionDeploymentBody {
        FunctionDeploymentBody {
            location: Box::new(location),
            replicas: Box::new(replicas),
        }
    }
}


