/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// FunctionType : Type of function, worker types are not exposed to ingress routes

#[allow(unused_imports)]
use crate::models;

/// Type of function, worker types are not exposed to ingress routes
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FunctionType {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "worker")]
    Worker,

}

impl ToString for FunctionType {
    fn to_string(&self) -> String {
        match self {
            Self::Http => String::from("http"),
            Self::Worker => String::from("worker"),
        }
    }
}

impl Default for FunctionType {
    fn default() -> FunctionType {
        Self::Http
    }
}




