/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FunctionDeployment {
    /// ID of the deployment
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "location")]
    pub location: Box<models::Location>,
    #[serde(rename = "replicas")]
    pub replicas: Box<models::FunctionReplicas>,
}

impl FunctionDeployment {
    pub fn new(location: models::Location, replicas: models::FunctionReplicas) -> FunctionDeployment {
        FunctionDeployment {
            id: None,
            location: Box::new(location),
            replicas: Box::new(replicas),
        }
    }
}


