/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// FunctionEnv : Environment variable for function

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FunctionEnv {
    /// Key name
    #[serde(rename = "name")]
    pub name: String,
    /// Reference to the secret to use
    #[serde(rename = "reference")]
    pub reference: String,
}

impl FunctionEnv {
    /// Environment variable for function
    pub fn new(name: String, reference: String) -> FunctionEnv {
        FunctionEnv {
            name,
            reference,
        }
    }
}


