/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// FunctionReplicas : Balancing logic

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FunctionReplicas {
    /// Minimum number of replicas to have
    #[serde(rename = "min")]
    pub min: i32,
    /// Maximum number of replicas to have
    #[serde(rename = "max")]
    pub max: i32,
    #[serde(rename = "affinity")]
    pub affinity: Box<models::FunctionReplicasAffinity>,
}

impl FunctionReplicas {
    /// Balancing logic
    pub fn new(min: i32, max: i32, affinity: models::FunctionReplicasAffinity) -> FunctionReplicas {
        FunctionReplicas {
            min,
            max,
            affinity: Box::new(affinity),
        }
    }
}


