/*
 * Chaos
 *
 * Management API - Central user exposed system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetProjectFunctionsSuccessResponseSchemaInnerLocationAwsScaling {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "average")]
    pub average: f32,
}

impl GetProjectFunctionsSuccessResponseSchemaInnerLocationAwsScaling {
    pub fn new(r#type: String, average: f32) -> GetProjectFunctionsSuccessResponseSchemaInnerLocationAwsScaling {
        GetProjectFunctionsSuccessResponseSchemaInnerLocationAwsScaling {
            r#type,
            average,
        }
    }
}


