/*
 * Chaos
 *
 * Management API - Central user exposed system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetProjects200ResponseInner {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "org")]
    pub org: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
}

impl GetProjects200ResponseInner {
    pub fn new(id: i32, org: i32, name: String, slug: String) -> GetProjects200ResponseInner {
        GetProjects200ResponseInner {
            id,
            org,
            name,
            slug,
        }
    }
}


