/*
 * Chaos
 *
 * Management API - Central user exposed system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetProvidersSuccessResponseSchemaInner {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "regions")]
    pub regions: Vec<String>,
    #[serde(rename = "cities")]
    pub cities: Vec<String>,
}

impl GetProvidersSuccessResponseSchemaInner {
    pub fn new(provider: String, regions: Vec<String>, cities: Vec<String>) -> GetProvidersSuccessResponseSchemaInner {
        GetProvidersSuccessResponseSchemaInner {
            provider,
            regions,
            cities,
        }
    }
}


