/*
 * Chaos
 *
 * Management API - Central user exposed system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetProjectFunctionsSuccessResponseSchemaInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "build")]
    pub build: Box<crate::models::GetProjectFunctionsSuccessResponseSchemaInnerBuild>,
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "route")]
    pub route: Box<crate::models::GetProjectFunctionsSuccessResponseSchemaInnerRoute>,
    #[serde(rename = "location")]
    pub location: Box<crate::models::GetProjectFunctionsSuccessResponseSchemaInnerLocation>,
}

impl GetProjectFunctionsSuccessResponseSchemaInner {
    pub fn new(id: String, name: String, description: String, build: crate::models::GetProjectFunctionsSuccessResponseSchemaInnerBuild, image: String, route: crate::models::GetProjectFunctionsSuccessResponseSchemaInnerRoute, location: crate::models::GetProjectFunctionsSuccessResponseSchemaInnerLocation) -> GetProjectFunctionsSuccessResponseSchemaInner {
        GetProjectFunctionsSuccessResponseSchemaInner {
            id,
            name,
            description,
            build: Box::new(build),
            image,
            route: Box::new(route),
            location: Box::new(location),
        }
    }
}


