/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// HostBody : Host body

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HostBody {
    /// Hostname, this can be the root of a domain or a subdomain
    #[serde(rename = "host")]
    pub host: String,
    /// The secret reference to the certificate
    #[serde(rename = "certificate")]
    pub certificate: String,
    /// If the host is disabled, then this host won't be accessible and so the deployments will not be routable
    #[serde(rename = "disabled")]
    pub disabled: bool,
}

impl HostBody {
    /// Host body
    pub fn new(host: String, certificate: String, disabled: bool) -> HostBody {
        HostBody {
            host,
            certificate,
            disabled,
        }
    }
}


