/*
 * Chaos
 *
 * Management API (Central System)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "location")]
    pub location: crate::models::ClustersLocation,
    #[serde(rename = "provider")]
    pub provider: String,
}

impl InlineObject {
    pub fn new(name: String, address: String, location: crate::models::ClustersLocation, provider: String) -> InlineObject {
        InlineObject {
            name,
            address,
            location,
            provider,
        }
    }
}


