/*
 * Chaos
 *
 * Management API - Central user exposed system
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse200 {
    #[serde(rename = "status")]
    pub status: String,
}

impl InlineResponse200 {
    pub fn new(status: String) -> InlineResponse200 {
        InlineResponse200 {
            status,
        }
    }
}


