/*
 * Chaos
 *
 * Management API (Central System)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject {
    #[serde(rename = "project")]
    pub project: crate::models::BatchProject,
    #[serde(rename = "functions")]
    pub functions: Vec<crate::models::BatchFunctions>,
}

impl InlineObject {
    pub fn new(project: crate::models::BatchProject, functions: Vec<crate::models::BatchFunctions>) -> InlineObject {
        InlineObject {
            project,
            functions,
        }
    }
}


