/*
 * Chaos
 *
 * Management API (Central System)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse200 {
    #[serde(rename = "id")]
    pub id: f32,
    #[serde(rename = "token")]
    pub token: String,
}

impl InlineResponse200 {
    pub fn new(id: f32, token: String) -> InlineResponse200 {
        InlineResponse200 {
            id,
            token,
        }
    }
}


