/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ListHosts : List of projects hosts



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListHosts {
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
    #[serde(rename = "data")]
    pub data: Vec<crate::models::Host>,
}

impl ListHosts {
    /// List of projects hosts
    pub fn new(meta: crate::models::PaginationMeta, data: Vec<crate::models::Host>) -> ListHosts {
        ListHosts {
            meta: Box::new(meta),
            data,
        }
    }
}


