/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ListAuthTokens : List of auth tokens

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAuthTokens {
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
    #[serde(rename = "data")]
    pub data: Vec<models::AuthTokenMeta>,
}

impl ListAuthTokens {
    /// List of auth tokens
    pub fn new(meta: models::PaginationMeta, data: Vec<models::AuthTokenMeta>) -> ListAuthTokens {
        ListAuthTokens {
            meta: Box::new(meta),
            data,
        }
    }
}


