/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ListFunction : List of functions

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListFunction {
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
    #[serde(rename = "data")]
    pub data: Vec<models::Function>,
}

impl ListFunction {
    /// List of functions
    pub fn new(meta: models::PaginationMeta, data: Vec<models::Function>) -> ListFunction {
        ListFunction {
            meta: Box::new(meta),
            data,
        }
    }
}


