/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ListOrganisationResponse : List organisations schema



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListOrganisationResponse {
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
    #[serde(rename = "data")]
    pub data: Vec<models::OrganisationResponse>,
}

impl ListOrganisationResponse {
    /// List organisations schema
    pub fn new(meta: models::PaginationMeta, data: Vec<models::OrganisationResponse>) -> ListOrganisationResponse {
        ListOrganisationResponse {
            meta: Box::new(meta),
            data,
        }
    }
}


