/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ListSecretResponse : List of secrets



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListSecretResponse {
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PaginationMeta>,
    #[serde(rename = "data")]
    pub data: Vec<crate::models::SecretMetaResponse>,
}

impl ListSecretResponse {
    /// List of secrets
    pub fn new(meta: crate::models::PaginationMeta, data: Vec<crate::models::SecretMetaResponse>) -> ListSecretResponse {
        ListSecretResponse {
            meta: Box::new(meta),
            data,
        }
    }
}


