/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ListProviderResponse : List of providers

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListProviderResponse {
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMeta>,
    #[serde(rename = "data")]
    pub data: Vec<models::Provider>,
}

impl ListProviderResponse {
    /// List of providers
    pub fn new(meta: models::PaginationMeta, data: Vec<models::Provider>) -> ListProviderResponse {
        ListProviderResponse {
            meta: Box::new(meta),
            data,
        }
    }
}


