/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsListFTimestampsParameter {
    /// Restrict to after this timestamp
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
    /// Resitrct to before this timestamp
    #[serde(rename = "before", skip_serializing_if = "Option::is_none")]
    pub before: Option<String>,
}

impl LogsListFTimestampsParameter {
    pub fn new() -> LogsListFTimestampsParameter {
        LogsListFTimestampsParameter {
            after: None,
            before: None,
        }
    }
}


