/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

use super::MetricHttpAggregation;
use super::MetricResourceAggregation;

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MetricsAggregationsList200Response {
    MetricHttpAggregation(Box<MetricHttpAggregation>),
    MetricResourceAggregation(Box<MetricResourceAggregation>),
}

impl Default for MetricsAggregationsList200Response {
    fn default() -> Self {
        Self::MetricHttpAggregation(Box::new(MetricHttpAggregation::default()))
    }
}


