/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricHttpAggregation : Metric http aggregation

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricHttpAggregation {
    #[serde(rename = "http_codes", skip_serializing_if = "Option::is_none")]
    pub http_codes: Option<Box<models::MetricHttpAggregationHttpCodes>>,
}

impl MetricHttpAggregation {
    /// Metric http aggregation
    pub fn new() -> MetricHttpAggregation {
        MetricHttpAggregation {
            http_codes: None,
        }
    }
}


