/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricHttpAggregationHttpCodesBucketsInner : HTTP status code bucket

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricHttpAggregationHttpCodesBucketsInner {
    /// Number of documents in the bucket
    #[serde(rename = "doc_count", skip_serializing_if = "Option::is_none")]
    pub doc_count: Option<i32>,
    #[serde(rename = "histogram", skip_serializing_if = "Option::is_none")]
    pub histogram: Option<Box<models::MetricHttpAggregationHttpCodesBucketsInnerHistogram>>,
    /// HTTP status code, typical values will be;  - http-2xx - http-3xx - http-4xx - http-5xx  > Note: the 'xx' is intentional and literal, all status codes within that range will be grouped 
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl MetricHttpAggregationHttpCodesBucketsInner {
    /// HTTP status code bucket
    pub fn new() -> MetricHttpAggregationHttpCodesBucketsInner {
        MetricHttpAggregationHttpCodesBucketsInner {
            doc_count: None,
            histogram: None,
            key: None,
        }
    }
}


