/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricResourceAggregationResourcesBucketsInner : Histogram bucket

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricResourceAggregationResourcesBucketsInner {
    /// Number of documents in the bucket
    #[serde(rename = "doc_count", skip_serializing_if = "Option::is_none")]
    pub doc_count: Option<i32>,
    #[serde(rename = "histogram", skip_serializing_if = "Option::is_none")]
    pub histogram: Option<Box<models::MetricResourceAggregationResourcesBucketsInnerHistogram>>,
    /// Metric key
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl MetricResourceAggregationResourcesBucketsInner {
    /// Histogram bucket
    pub fn new() -> MetricResourceAggregationResourcesBucketsInner {
        MetricResourceAggregationResourcesBucketsInner {
            doc_count: None,
            histogram: None,
            key: None,
        }
    }
}


