/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricResourceAggregation : Metric resource aggregation

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricResourceAggregation {
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Box<models::MetricResourceAggregationResources>>,
}

impl MetricResourceAggregation {
    /// Metric resource aggregation
    pub fn new() -> MetricResourceAggregation {
        MetricResourceAggregation {
            resources: None,
        }
    }
}


