/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// MetricHttpAggregationHttpCodesBucketsInnerHistogram : Histogram of http status code usage

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetricHttpAggregationHttpCodesBucketsInnerHistogram {
    /// Array of unqiue resources
    #[serde(rename = "buckets", skip_serializing_if = "Option::is_none")]
    pub buckets: Option<Vec<models::MetricResourceAggregationResourcesBucketsInner>>,
}

impl MetricHttpAggregationHttpCodesBucketsInnerHistogram {
    /// Histogram of http status code usage
    pub fn new() -> MetricHttpAggregationHttpCodesBucketsInnerHistogram {
        MetricHttpAggregationHttpCodesBucketsInnerHistogram {
            buckets: None,
        }
    }
}


