/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// NotFoundResponse : Resource not found



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NotFoundResponse {
    #[serde(rename = "message")]
    pub message: String,
}

impl NotFoundResponse {
    /// Resource not found
    pub fn new(message: String) -> NotFoundResponse {
        NotFoundResponse {
            message,
        }
    }
}


