/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganisationsListPageParameter {
    /// Offset
    #[serde(rename = "before", skip_serializing_if = "Option::is_none")]
    pub before: Option<i32>,
    /// Offset
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<i32>,
    /// Limit
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
}

impl OrganisationsListPageParameter {
    pub fn new() -> OrganisationsListPageParameter {
        OrganisationsListPageParameter {
            before: None,
            after: None,
            size: None,
        }
    }
}


