/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// OrganisationResponse : Organisation response



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganisationResponse {
    /// Organisation id
    #[serde(rename = "id")]
    pub id: String,
    /// User id
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// Organisation name
    #[serde(rename = "name")]
    pub name: String,
}

impl OrganisationResponse {
    /// Organisation response
    pub fn new(id: String, user_id: String, name: String) -> OrganisationResponse {
        OrganisationResponse {
            id,
            user_id,
            name,
        }
    }
}


