/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// PaginationLinks : Links object for pagination use



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaginationLinks {
    #[serde(rename = "prev")]
    pub prev: String,
    #[serde(rename = "next")]
    pub next: String,
}

impl PaginationLinks {
    /// Links object for pagination use
    pub fn new(prev: String, next: String) -> PaginationLinks {
        PaginationLinks {
            prev,
            next,
        }
    }
}


