/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// PaginationMeta : Meta object for pagination use



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaginationMeta {
    #[serde(rename = "results")]
    pub results: i32,
    #[serde(rename = "start")]
    pub start: i32,
    #[serde(rename = "end")]
    pub end: i32,
    #[serde(rename = "pages")]
    pub pages: i32,
    #[serde(rename = "links")]
    pub links: Box<models::PaginationLinks>,
}

impl PaginationMeta {
    /// Meta object for pagination use
    pub fn new(results: i32, start: i32, end: i32, pages: i32, links: models::PaginationLinks) -> PaginationMeta {
        PaginationMeta {
            results,
            start,
            end,
            pages,
            links: Box::new(links),
        }
    }
}


