/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// PaginationMeta : Meta object for pagination use



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaginationMeta {
    #[serde(rename = "results")]
    pub results: f32,
    #[serde(rename = "start")]
    pub start: f32,
    #[serde(rename = "end")]
    pub end: f32,
    #[serde(rename = "pages")]
    pub pages: f32,
    #[serde(rename = "links")]
    pub links: Box<crate::models::PaginationLinks>,
}

impl PaginationMeta {
    /// Meta object for pagination use
    pub fn new(results: f32, start: f32, end: f32, pages: f32, links: crate::models::PaginationLinks) -> PaginationMeta {
        PaginationMeta {
            results,
            start,
            end,
            pages,
            links: Box::new(links),
        }
    }
}


