/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ProjectBodyPatch : Project patch fields



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectBodyPatch {
    /// Organisation id
    #[serde(rename = "org_id", skip_serializing_if = "Option::is_none")]
    pub org_id: Option<uuid::Uuid>,
    /// Project name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ProjectBodyPatch {
    /// Project patch fields
    pub fn new() -> ProjectBodyPatch {
        ProjectBodyPatch {
            org_id: None,
            name: None,
        }
    }
}


