/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ProjectResponse : Project response



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectResponse {
    /// Project id
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Organisation id
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    /// Project name
    #[serde(rename = "name")]
    pub name: String,
}

impl ProjectResponse {
    /// Project response
    pub fn new(id: uuid::Uuid, org_id: uuid::Uuid, name: String) -> ProjectResponse {
        ProjectResponse {
            id,
            org_id,
            name,
        }
    }
}


