/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ProjectBody : Project body

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectBody {
    /// Organisation id
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    /// Project name
    #[serde(rename = "name")]
    pub name: String,
}

impl ProjectBody {
    /// Project body
    pub fn new(org_id: uuid::Uuid, name: String) -> ProjectBody {
        ProjectBody {
            org_id,
            name,
        }
    }
}


