/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// Provider : List of providers

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Provider {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Name of provider
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "locations")]
    pub locations: Box<models::ProviderLocations>,
}

impl Provider {
    /// List of providers
    pub fn new(id: uuid::Uuid, name: String, locations: models::ProviderLocations) -> Provider {
        Provider {
            id,
            name,
            locations: Box::new(locations),
        }
    }
}


