/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// ProviderLocations : Locations at varying levels this provider operates within

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProviderLocations {
    #[serde(rename = "continents")]
    pub continents: Vec<String>,
    #[serde(rename = "countries")]
    pub countries: Vec<String>,
    #[serde(rename = "cities")]
    pub cities: Vec<String>,
}

impl ProviderLocations {
    /// Locations at varying levels this provider operates within
    pub fn new(continents: Vec<String>, countries: Vec<String>, cities: Vec<String>) -> ProviderLocations {
        ProviderLocations {
            continents,
            countries,
            cities,
        }
    }
}


