/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// SecretMetaType : Secrets types: registry, certificate, environment, dek

/// Secrets types: registry, certificate, environment, dek
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecretMetaType {
    #[serde(rename = "registry")]
    Registry,
    #[serde(rename = "certificate")]
    Certificate,
    #[serde(rename = "environment")]
    Environment,
    #[serde(rename = "dek")]
    Dek,

}

impl ToString for SecretMetaType {
    fn to_string(&self) -> String {
        match self {
            Self::Registry => String::from("registry"),
            Self::Certificate => String::from("certificate"),
            Self::Environment => String::from("environment"),
            Self::Dek => String::from("dek"),
        }
    }
}

impl Default for SecretMetaType {
    fn default() -> SecretMetaType {
        Self::Registry
    }
}




