/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// SecretCertificate : Encrypted SSL private key and plain certificate. Certificate expected in x509 pem format, key expected in pkcs8 or pkcs1 pem format. `type: certificate`



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecretCertificate {
    /// Public certificate
    #[serde(rename = "certificate")]
    pub certificate: String,
    /// Encrypted certificate private key
    #[serde(rename = "certificate_value")]
    pub certificate_value: String,
}

impl SecretCertificate {
    /// Encrypted SSL private key and plain certificate. Certificate expected in x509 pem format, key expected in pkcs8 or pkcs1 pem format. `type: certificate`
    pub fn new(certificate: String, certificate_value: String) -> SecretCertificate {
        SecretCertificate {
            certificate,
            certificate_value,
        }
    }
}


