/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// SecretCreateType : Secrets types: registry, certificate, environment

/// Secrets types: registry, certificate, environment
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecretCreateType {
    #[serde(rename = "registry")]
    Registry,
    #[serde(rename = "certificate")]
    Certificate,
    #[serde(rename = "environment")]
    Environment,

}

impl ToString for SecretCreateType {
    fn to_string(&self) -> String {
        match self {
            Self::Registry => String::from("registry"),
            Self::Certificate => String::from("certificate"),
            Self::Environment => String::from("environment"),
        }
    }
}

impl Default for SecretCreateType {
    fn default() -> SecretCreateType {
        Self::Registry
    }
}




