/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// SecretEnvironment : Encrypted ENV secret, `type: environment`

#[allow(unused_imports)]
use crate::models;



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecretEnvironment {
    /// Encrypted environment value
    #[serde(rename = "environment_value")]
    pub environment_value: String,
}

impl SecretEnvironment {
    /// Encrypted ENV secret, `type: environment`
    pub fn new(environment_value: String) -> SecretEnvironment {
        SecretEnvironment {
            environment_value,
        }
    }
}


