/*
 * Chaos
 *
 * Central Management API - publicly exposed set of APIs for managing deployments
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qernal.com
 * Generated by: https://openapi-generator.tech
 */

/// SecretMetaResponseRegistryPayload : Secret metadata registry payload



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecretMetaResponseRegistryPayload {
    /// Registry domain
    #[serde(rename = "registry")]
    pub registry: String,
}

impl SecretMetaResponseRegistryPayload {
    /// Secret metadata registry payload
    pub fn new(registry: String) -> SecretMetaResponseRegistryPayload {
        SecretMetaResponseRegistryPayload {
            registry,
        }
    }
}


